version: "3.9"
    
volumes:
  cassandra_data:
    driver: local

services:
    cassandra:
        image: 'bitnami/cassandra:latest'
        container_name: cassandra
        volumes:
            - 'cassandra_data:/bitnami'
            - .:/docker-entrypoint-initdb.d
        ports:
            - '7000:7000'
            - '9042:9042'
        environment:
            - CASSANDRA_PASSWORD=cassandra
            
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        container_name: zookeeper
        restart: always    
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
               
    kafka:
        image: 'bitnami/kafka:latest'
        container_name: kafka
        ports:
          - '9093:9093'
        environment:
          - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
          - ALLOW_PLAINTEXT_LISTENER=yes
          - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
          - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
          - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
          - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
        depends_on:
          - zookeeper

    hazi:
        image: 'hazi:latest'
        container_name: hazi_backend
        restart: always
        ports:
          - '8080:8080'
        environment:
          - spring_data_cassandra_contact-points=cassandra
          - spring_data_cassandra_port=9042
          - spring_data_cassandra_keyspace-name=hazi
          - spring_data_cassandra_local-datacenter=datacenter1
          - spring_data_cassandra_password=cassandra
          - spring_data_cassandra_username=cassandra
          - spring_kafka_bootstrap-servers=kafka:9092
          - spring_kafka_consumer_group-id=group_id
        depends_on:
          - cassandra
          - kafka
          
    hazi_frontend:
        image: 'hazi_frontend:latest'
        container_name: hazi_frontend
        ports:
          - '80:80'
        environment:
          - REACT_APP_BACKEND_URL=localhost:8080