apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hazi
  name: hazi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hazi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hazi
    spec:
      containers:
      - image: localhost:5000/hazi
        name: hazi
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hazi
  name: hazi
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hazi
  type: ClusterIP
status:
  loadBalancer: {}
